// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrnoslynzrjroawoifyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxybm9zbHluenJqcm9hd29pZnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODg3MzcsImV4cCI6MjA1OTg2NDczN30.CYivwK5KhM_fUkros2DtLaqfAQUPbcTgj-rDYgIid7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);